# Generated by Django 3.0.8 on 2020-07-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authortag',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usertag',
            old_name='title',
            new_name='name',
        ),
    ]
