# Generated by Django 3.2.7 on 2021-11-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200721_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['published']},
        ),
        migrations.AlterField(
            model_name='article',
            name='author_tags',
            field=models.ManyToManyField(blank=True, null=True, to='api.AuthorTag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comments_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_tags',
            field=models.ManyToManyField(blank=True, null=True, to='api.UserTag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='words_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
