# Generated by Django 3.2.7 on 2021-11-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211102_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_tags',
            field=models.ManyToManyField(blank=True, to='api.AuthorTag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_tags',
            field=models.ManyToManyField(blank=True, to='api.UserTag'),
        ),
    ]
