# Generated by Django 4.0.1 on 2025-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211102_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='authortag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='usertag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='authortag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authortag',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
